/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import java.sql.Timestamp;
import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 07-01-2016
 * 
 * XDoclet definition:
 * @struts.form name="addPointForm"
 */
public class AddPointForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** id property */
	private String id;

	/** createTime property */
	private Timestamp createTime;

	/** fieldNum property */
	private Integer fieldNum;

	/** fieldType property */
	private String fieldType;

	/** fieldLoc property */
	private String fieldLoc;

	/** pointNum property */
	private Integer pointNum;

	/** fieldSquare property */
	private String fieldSquare;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/** 
	 * Returns the createTime.
	 * @return Timestamp
	 */
	public Timestamp getCreateTime() {
		return createTime;
	}

	/** 
	 * Set the createTime.
	 * @param createTime The createTime to set
	 */
	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}

	/** 
	 * Returns the fieldNum.
	 * @return Integer
	 */
	public Integer getFieldNum() {
		return fieldNum;
	}

	/** 
	 * Set the fieldNum.
	 * @param fieldNum The fieldNum to set
	 */
	public void setFieldNum(Integer fieldNum) {
		this.fieldNum = fieldNum;
	}

	/** 
	 * Returns the fieldType.
	 * @return String
	 */
	public String getFieldType() {
		return fieldType;
	}

	/** 
	 * Set the fieldType.
	 * @param fieldType The fieldType to set
	 */
	public void setFieldType(String fieldType) {
		this.fieldType = fieldType;
	}

	/** 
	 * Returns the fieldLoc.
	 * @return String
	 */
	public String getFieldLoc() {
		return fieldLoc;
	}

	/** 
	 * Set the fieldLoc.
	 * @param fieldLoc The fieldLoc to set
	 */
	public void setFieldLoc(String fieldLoc) {
		this.fieldLoc = fieldLoc;
	}

	/** 
	 * Returns the pointNum.
	 * @return Integer
	 */
	public Integer getPointNum() {
		return pointNum;
	}

	/** 
	 * Set the pointNum.
	 * @param pointNum The pointNum to set
	 */
	public void setPointNum(Integer pointNum) {
		this.pointNum = pointNum;
	}

	/** 
	 * Returns the fieldSquare.
	 * @return String
	 */
	public String getFieldSquare() {
		return fieldSquare;
	}

	/** 
	 * Set the fieldSquare.
	 * @param fieldSquare The fieldSquare to set
	 */
	public void setFieldSquare(String fieldSquare) {
		this.fieldSquare = fieldSquare;
	}
}