/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.beans.Pointbase;
import com.dao.PointbaseDao;
import com.struts.form.DeletePointForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-01-2016
 * 
 * XDoclet definition:
 * @struts.action path="/deletePoint" name="deletePointForm" input="/pointer/pointer.jsp" scope="request" validate="true"
 * @struts.action-forward name="fail" path="/pointer/pointer.jsp"
 * @struts.action-forward name="success" path="/pointer/pointer.jsp"
 */
public class DeletePointAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DeletePointForm deletePointForm = (DeletePointForm) form;// TODO Auto-generated method stub
		Integer pointNum=deletePointForm.getPointNum();
		//新建一个对象，对于数据进行操作
		PointbaseDao PD=new  PointbaseDao();
		PD.deletePointbase(pointNum);
		ArrayList<Pointbase> pb=PD.searchAll();
		request.setAttribute("pb",pb);
		if(pb.size()>0){
		//System.out.println(pointNum+"00000000");
		return mapping.findForward("success");
		}
		else{
			return mapping.findForward("fail");
		}
	}
}